services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: deram
      POSTGRES_PASSWORD: deram1t2s
      POSTGRES_DB: material_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deram -d material_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend